[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

This project aims to develop a mobile radar, that allows any user to track the location of other added users to the system. The system can be accesed via website.

=== Requirements Overview

[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****
We are to develop a mobile and web application for the localization of different ussers in the system.

The functionality that the application will provide:

. Registration in the system.

. Adding of other ussers.

. Localization of added ussers.

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****
[options="header",cols="1,2"]
|===
|Quality goal|Motivation
| _Understandability_ | _Any user should be able to easily understand and comprehend the functionality and ussage_ 
| _Attractiveness_ | _The user interface should be attractive to pottential ussers_ 
| _Security_ | _The data of any usser should be properly protected_ 
| _Testability_ | _The application should be able to go through different test_ 
|===

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2"]
|===
|Role/Name|Expectations
| _Clients_ | _Those who asked for the development of the project. They expect a fully functional application allowing for the usage of the radar._
| _Development team_ | _Those in charge of developing the application, expecting to learn about new technologies._
| _Users_ | _Those who will use the application. They will expect a simple to understand interface and the least ammount of complications._
|===
