[[section-solution-strategy]]
== Solution Strategy


[role="arc42help"]
****
.Contents
Our main technologies will be React for the front-end and Solid for the front-end.

.Motivation
The main reasons are the compatibility between those tools and that we have some knowledge of JavaScript.

.Form
There is plenty of information on the internet about how to use solid and react, both of these technologies have a big community behind, that gave us some peace of mind, the fact that knowing we could get help in puntual moments is crucial to develop such a difficult project.


///
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape the system's architecture. These include

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the basis for many other detailed decisions or implementation rules.

.Form
Keep the explanation of these key decisions short.

Motivate what you have decided and why you decided that way,
based upon your problem statement, the quality goals and key constraints.
Refer to details in the following sections.
///

****
