[[section-runtime-view]]
== Runtime View


=== Log in

A potential user may log in the application via the log in screen. Log in comences upon entering the application.

1. The user enters their credentials, such as their username and password.
2. The user touches the log in button.
3. The application, if the log in is valid, returns the functionality of the application.

[plantuml,"Log in diagram",png]
----
actor User
User -> Radarin: Enters credentials
User -> Radarin: Touches log in button
Radarin -> Pod: Log in request
Pod -> Radarin: Log in response
Radarin -> User: Shows content
----

=== Register friends

1. User1 touches the "add a friend" button.
2. User1 enters said friend's WebID.
3. User1 application sends a petition to User2 Pod with the information.
4. User2 Pod notifies User2 application.
5. User2 application waits for confirmation on the friend request from User2.
6. User2 touches the "accept friend request" button.
7. User2 application sends the information to User2 Pod.
8. User2 Pod registers User1 as a friend, and sends the confirmation to User1 application.
9. User1 application sends the information to User1 Pod.
10. User1 application notifies User1.

[plantuml,"Register friends diagram",png]
----
actor User1
actor User2
User1 -> User1 Application: Touches the add a friend button
User1 -> User1 Application: Enters a friend's WebID
User1 Application --> User2Pod: Sends petition
User2Pod -> User2 Application: Notifies petition
User2 Application --> User2: Wait for confirmation
User2 -> User2 Application: Touches the accept request button
User2 Application -> User2Pod: Sends confirmation
User2Pod -> User2Pod: Register User1 as friend
User2Pod -> User1 Application: Sends confirmation
User1 Application -> User1Pod: Sends confirmation
User1 Application -> User1: Notifies confirmation
----

=== Geolocate friends

1. The user access the application.
2. The application request the localization of added friends in the friend list.
3. Connected friends send back the localization.
4. The application shows the user a map with the localization of said friends.

[plantuml,"Geolocate friends diagram",png]
----
actor User
User -> Radarin: Access application
Radarin -> FriendsPods: Request localization
FriendsPods -> Radarin: Provides localization
Radarin -> User: Shows friends location
----


