[[section-runtime-view]]
== Runtime View


=== Log in

A potential user may log in the application via the log in screen. Log in comences upon entering the application.

1. The user enters their credentials, such as their username and password.
2. The user touches the log in button.
3. The application, if the log in is valid, returns the functionality of the application.

[plantuml,"Log in diagram",png]
----
actor User
User -> Radarin: Enters credentials
User -> Radarin: Touches log in button
Radarin -> Pod: Log in request
Pod -> Radarin: Log in response
Radarin -> User: Shows content
----

=== Register friends

1. The user touches the "add a friend" button.
2. The user enters said friend's WebID.
3. The application sends a petition to the associated Pod.
4. Said Pod sends back a confirmation.
5. The user is shown the new friend in their friends list.

[plantuml,"Register friends diagram",png]
----
actor User
User -> Radarin: Touches the add a friend button
User -> Radarin: Enters a friend's WebID
Radarin -> FriendPod: Sends petition
FriendPod -> Radarin: Sends confirmation
Radarin -> User: Shows updated friend list
----

=== Geolocate friends

1. The user access the application.
2. The application request the localization of added friends in the friend list.
3. Connected friends send back the localization.
4. The application shows the user a map with the localization of said friends.

[plantuml,"Geolocate friends diagram",png]
----
actor User
User -> Radarin: Access application
Radarin -> FriendsPods: Request localization
FriendsPods -> Radarin: Provides localization
Radarin -> User: Shows friends location
----


