[[section-anexos]]
== Annexed

=== Tests

The webb app and the REST API have been tested in order to solve the biggest ammount of issues

==== Webapp

===== Unitary testing 

We have done tests about the main parts of the webapp:

* Interface :

** The app is rendered as spected, whatever the size of the screen is.
** The interface changes if the user is logged, a regular user is using the app or the admin is using the app.
** All the components show the spected info.
** The admin window works as spected and anly appears if the admin is the logged user.
** The login web page (Inrupt) is showed fine and redirects from and back to Radarin.

===== Acceptance and stress tests

We did some acceptance and stress tests to the system to prove if the environment can deal with this kind of situations.

We logged with all of our PODs, in order to simulate a real world situation. In all the PODs we did the following

*Beggining: The user logged on in his POD with friends.

*Actions performed: The user looked for the friends on the map, and changed the area for the search

*End: The user checked that all of their friends were in the list.

*Results: The webapp performed well, with reduced loadtimes, mostly in the communication with the PODs service. All the users could do the tasks.
==== Mobile app

===== Unitary Testing

We reproduced the same tests from the webapp.
The information deployed shows perfectly fine for load format screens and the app is functional.
Taking into account the facility of moving around with the phone, we proved that the real time location works, that means:

* The user's mark moves while he moves.
* The other users can se it.
* The notifications work fine.

===== Automatic tests
Some automatic tests where developed, in order to automatize the task of debug the code.
All the tests run automatic at the deploying task, and can be run locally by calling "npm -test".
With this, we acomplish:
* Increase the code coverage, which means that the code have the smallest ammount of errors as possible.
* Ensure that the system works as spected.
* Find improvement niches